name: XRayAlerts
main: LinlinSaya.mc.rayalerts.XRayAlertsPlugin
version: 2.0.2
author: linlin
description: 檢測並警報可能使用 X-Ray 作弊的玩家
api-version: '1.20'
commands:
  xrayalerts:
    description: "X-Ray 礦物警報系統"
    usage: "/xrayalerts [test|reload]"
    aliases: [xray]
    permission-message: "§c您沒有權限執行此命令。"
permissions:
  xrayalerts.ignore:
    description: "防止玩家觸發 X-Ray 警報"
    default: false
  xrayalerts.receive:
    description: "允許接收潛在的 X-Ray 警報通知"
    default: op
  xrayalerts.toggle:
    description: "允許開關潛在的 X-Ray 警報通知"
    default: op
  xrayalerts.admin:
    description: "允許管理插件設置和測試功能"
    default: op
