# 挖礦模式設定: "block" (每個方塊獨立檢測) 或 "vein" (檢測整個礦脈)
mode: "block" # 選項: "block", "vein"

# Discord Webhook 設定
discord:
  enabled: false # 是否啟用 Discord Webhook 通知
  webhook-url: "" # 在此填入你的 Discord Webhook URL

monitored-blocks:
  - ANCIENT_DEBRIS
  - DEEPSLATE_DIAMOND_ORE
  - DIAMOND_ORE
